# Generated by Django 6.0.4 on 2026-04-21 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0002_remove_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_tashkent', models.BooleanField(default=True)),
                ('address_name', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('street', models.CharField(max_length=255)),
                ('home', models.CharField(max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('created', 'Buyurtma yaratildi'), ('confirming', 'Buyurtma tasdiqlanish jarayonida'), ('preparing', 'Kuryer buyurtmani tayyorlamoqda'), ('sent_to_fargo', 'Buyurtma fargo punktga topshirildi'), ('delivered', 'Buyurtma mijozga topshirildi'), ('returned', 'Buyurtma qaytarildi'), ('at_fargo', 'Buyurtma fargo punktida'), ('to_region', 'Viloyatga yuborilmoqda'), ('region_received', 'Viloyat punktga topshirildi'), ('to_client', 'Mijozga yuborilmoqda'), ('failed_call', 'Kuryer mijoz bilan boglana olmadi')], default='created', max_length=30)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cash_card', 'Cash / Card'), ('merchant', 'Merchant')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='product.product')),
            ],
        ),
    ]
