# Generated by Django 5.2.13 on 2026-06-12 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to='product.product'),
        ),
    ]
